import { ArrowLeft, FileText, Sparkle } from '@phosphor-icons/react'
import type { Demo } from './api'
import { Button } from './ui'

const money = (value: number | null) => value === null ? 'Unknown' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: value !== 0 && Math.abs(value) < 0.01 ? 9 : 2 }).format(value)
const modelName = (route: string) => ({ baseline: 'Simple baseline', catboost: 'CatBoost', tabiclv2: 'TabICLv2' })[route] ?? route
const waiting = [
  { route: 'baseline', feature_set: 'structured' }, { route: 'catboost', feature_set: 'structured' },
  { route: 'catboost', feature_set: 'semantic' }, { route: 'tabiclv2', feature_set: 'structured' }, { route: 'tabiclv2', feature_set: 'semantic' },
]

export function DemoOverview({ demo, onClose }: { demo: Demo; onClose: () => void }) {
  const assumptions = demo.value.assumptions
  return <main className="reader demo-reader" aria-label="Business workflow demonstration">
    <header className="case-toolbar"><Button className="mobile-back" onClick={onClose} aria-label="Back to cases"><ArrowLeft size={18} /></Button><span className="case-number">{demo.demo_id}</span><span className="tag">{demo.status}</span></header>
    <div className="case-heading"><h1>{demo.title}</h1><div className="case-tags"><span className="source-tag">Synthetic business case</span><span className="tag">{demo.jev_mode}</span></div></div>
    <div className="reader-scroll"><div className="tab-content demo-content">
      {demo.error && <p role="alert" className="save-error">{demo.error}</p>}
      <section className="demo-section"><div className="record-heading"><strong>The work being automated</strong></div><p>{demo.problem}</p><details className="demo-details"><summary>How the work is done today</summary><ol>{demo.today.map(step => <li key={step}>{step}</li>)}</ol><p>The reviewer keeps responsibility for investigation and action.</p></details></section>
      <section className="demo-section" aria-label="Autonomous processing stages"><h2>From report to review</h2><p className="quiet-note">Stages show recorded evidence. Prepared inputs do not mean that Jev or prediction has run.</p>
        <ol className="demo-stages">{demo.stages.map(stage => <li key={stage.id}><span className={`demo-stage-dot ${stage.count ? 'observed' : ''}`} aria-hidden="true">{stage.count ? <Sparkle size={13} /> : <FileText size={13} />}</span><div><div className="record-heading"><strong>{stage.title}</strong><span>{stage.count ? `${stage.count} records observed` : demo.status === 'blocked' ? 'Not completed' : 'Awaiting execution'}</span></div><p>{stage.explanation}</p><span className="small-label">{stage.technology}</span></div></li>)}</ol>
      </section>
      {demo.workflow_rehearsal && <section className="demo-section" aria-label="Scheduled workflow rehearsal"><h2>Scheduled workflow rehearsal</h2><p><strong>{demo.workflow_rehearsal.status}</strong></p><p>{demo.workflow_rehearsal.scope_boundary}</p><span className="small-label">{demo.workflow_rehearsal.technology}</span>
        <div className="demo-table-wrap"><table className="demo-table"><thead><tr><th scope="col">Scenario</th><th scope="col">Completed jobs</th><th scope="col">Simulated forecasts</th><th scope="col">Delivery records</th></tr></thead><tbody>{demo.workflow_rehearsal.scenarios.map(row => <tr key={row.name}><th scope="row">{row.name}</th><td>{row.completed_jobs}</td><td>{row.simulated_predictions}</td><td>{row.delivery_records}</td></tr>)}</tbody></table></div>
        <p className="quiet-note">{demo.workflow_rehearsal.pending_triggers} pending triggers. {demo.workflow_rehearsal.replay_unchanged ? `Replay kept all ${demo.workflow_rehearsal.evidence_records} evidence records unchanged.` : 'Replay requires review.'} These results belong to the separate simulated rehearsal.</p>
      </section>}
      <section className="demo-section"><h2>Why compare two prediction models?</h2><p>They are alternatives for the same outcome. Compare facts alone with facts plus interpretation to check whether the extra work adds value.</p>{demo.comparison_basis && <p>{demo.comparison_basis}</p>}<div className="demo-table-wrap"><table className="demo-table"><thead><tr><th scope="col">Method</th><th scope="col">Inputs</th><th scope="col">Probability error</th><th scope="col">Run decision</th></tr></thead><tbody>{waiting.map(row => {
        const result = demo.comparisons.find(item => item.route === row.route && item.feature_set === row.feature_set)
        return <tr key={`${row.route}-${row.feature_set}`}><th scope="row">{modelName(row.route)}</th><td>{row.feature_set === 'semantic' ? 'Facts + Jev' : 'Facts only'}</td><td>{result?.metrics.brier === undefined || result.metrics.brier === null ? 'Not run' : result.metrics.brier.toFixed(4)}</td><td>{result ? result.selected ? 'Selected for this run' : 'Compared' : 'Pending'}</td></tr>
      })}</tbody></table></div><p className="quiet-note">Lower probability error is better. Selection uses validation error. Cost is shown separately. Synthetic results do not establish customer accuracy.</p></section>
      {demo.local_rehearsal && <section className="demo-section" aria-label="Local prediction rehearsal"><h2>What the local models predict</h2><p>{demo.local_rehearsal.scope_boundary}</p><div className="demo-table-wrap"><table className="demo-table"><thead><tr><th scope="col">Queue</th><th scope="col">Method</th><th scope="col">Chance of next-window breach</th></tr></thead><tbody>{demo.local_rehearsal.methods.flatMap(method => method.estimates.map(estimate => <tr key={`${method.route}-${estimate.entity}`}><th scope="row">{estimate.entity}</th><td>{modelName(method.route)}</td><td>{(estimate.value * 100).toFixed(1)}% <span className="quiet-note">· simulation windows {estimate.cutoff}–{estimate.target_at}</span></td></tr>))}</tbody></table></div><p className="quiet-note">These are synthetic examples. They do not establish real customer accuracy or business savings.</p></section>}
      <section className="demo-section" aria-label="Business value and execution cost"><h2>Value assumptions and execution cost</h2><div className="demo-value"><div><span>Illustrative weekly capacity change</span><strong>{demo.value.capacity_hours_per_week.toLocaleString('en-US')} hours</strong></div><div><span>Illustrative weekly labour capacity value</span><strong>{money(demo.value.capacity_value_usd_per_week)}</strong></div></div>
        <p className="quiet-note">Assumptions: {assumptions.cases_per_week} reports/week; {assumptions.manual_minutes_per_case} minutes manually and {assumptions.assisted_minutes_per_case} minutes assisted; {money(assumptions.labour_usd_per_hour)}/hour. Handling times have not been measured.</p>
        <dl className="demo-costs"><div><dt>Actual provider calls</dt><dd>{demo.actual_provider_calls ?? 'Unknown'}</dd></div>{demo.live_attempt && <div><dt>Retained request attempts</dt><dd>{demo.live_attempt.request_attempts}</dd></div>}<div><dt>Recorded provider charges</dt><dd>{money(demo.value.provider_usd)}</dd></div>{demo.live_attempt && <div><dt>Total retained attempt charge</dt><dd>{money(demo.live_attempt.total_provider_charge_usd)}</dd></div>}<div><dt>Compute cost</dt><dd>{money(demo.value.compute_usd)}</dd></div><div><dt>Net operating benefit</dt><dd>{money(demo.value.net_benefit_usd)}</dd></div><div><dt>Measured cash savings</dt><dd>Not measured</dd></div><div><dt>Attributed revenue gain</dt><dd>Not measured</dd></div></dl><p>{demo.value.explanation}</p>
      </section>
      <details className="demo-details"><summary>Technology components and their roles</summary><dl className="demo-stack">{demo.stack.map(component => <div key={component.name}><dt>{component.name}</dt><dd>{component.role}</dd></div>)}</dl></details>
      <section className="demo-section"><h2>What this run can establish</h2><ul>{demo.boundaries.map(boundary => <li key={boundary}>{boundary}</li>)}</ul><p className="quiet-note">Last scoped evidence refresh: {new Date(demo.captured_at).toLocaleTimeString()}</p><Button variant="outline" onClick={onClose}>Review the source and record a decision</Button></section>
    </div></div>
  </main>
}
